"""ShadowFillPoller — fills based on real trade events crossing hypothetical quotes.

Shadow Live Mode replaces the Poisson paper fill model with real market activity:

    For each live_trade at (token_id, trade_price, trade_size):
        if trade_price <= our_bid_price:
            → a taker sold at our bid → we buy (BUY fill)
        if trade_price >= our_ask_price:
            → a taker bought at our ask → we sell (SELL fill)

Fill size is min(our_level_size, trade_size) so a small taker trade only fills
what it can. No queue position model — we assume best position (optimistic), which
is the right assumption for strategy validation: if the strategy can't work even
with best-queue fills, it can't work live.

Key differences from paper Poisson mode:
  - Fill timing reflects real market activity (no fills when market is idle)
  - Adverse selection is real — price crossing your quote IS an information event
  - Fill rate reflects true market liquidity, not volume estimates
  - Markout metrics will measure actual post-fill price impact

Usage: set SHADOW=true in .env (requires PAPER=true — no real orders placed).
"""

import asyncio
import time
from maker.state import MakerState
from maker.types import Fill
from maker.fill_poller import FillPoller
from market.state import AppState
from utils.logger import get_logger

log = get_logger(__name__)


class ShadowFillPoller:
    """Fills hypothetical quotes when real trades cross our prices."""

    def __init__(
        self,
        app_state: AppState,
        maker_state: MakerState,
        fills_q: asyncio.Queue,
        trades_q: asyncio.Queue,
    ):
        self._app = app_state
        self._maker = maker_state
        self._fills_q = fills_q
        self._trades_q = trades_q  # (token_id, price, size) from CLOBMonitor

    def _check_fills(
        self,
        token_id: str,
        trade_price: float,
        trade_size: float,
        mid: float,
    ) -> list[Fill]:
        """Return fills generated by this trade event against live_orders."""
        fills = []
        now = time.time()

        levels = list(self._maker.live_orders.get(token_id, []))
        remaining_size = trade_size if trade_size > 0 else float("inf")

        for level in levels:
            if remaining_size <= 0:
                break

            bid_price = level.get("bid_price", 0.0)
            ask_price = level.get("ask_price", 1.0)
            bid_size = level.get("bid_size", 0.0)
            ask_size = level.get("ask_size", 0.0)
            bid_order_id = level.get("bid_order_id", "")
            ask_order_id = level.get("ask_order_id", "")

            # Trade crossed our bid — taker sold to us
            if bid_order_id and bid_size > 0 and trade_price <= bid_price:
                fill_size = min(bid_size, remaining_size)
                fills.append(Fill(
                    token_id=token_id,
                    side="BUY",
                    price=bid_price,
                    size=fill_size,
                    order_id=bid_order_id,
                    filled_at=now,
                    mid_at_fill=mid,
                ))
                remaining_size -= fill_size

            # Trade crossed our ask — taker bought from us
            if ask_order_id and ask_size > 0 and trade_price >= ask_price:
                fill_size = min(ask_size, remaining_size)
                fills.append(Fill(
                    token_id=token_id,
                    side="SELL",
                    price=ask_price,
                    size=fill_size,
                    order_id=ask_order_id,
                    filled_at=now,
                    mid_at_fill=mid,
                ))
                remaining_size -= fill_size

        return fills

    async def run(self):
        log.info("ShadowFillPoller running — fills driven by real trade events")
        while True:
            token_id, trade_price, trade_size = await self._trades_q.get()

            async with self._app._lock:
                cs = self._app.markets.get(token_id)
                mid = cs.mid if cs else trade_price

            fills = self._check_fills(token_id, trade_price, trade_size, mid)
            if not fills:
                continue

            FillPoller.consume_paper_fills(self._maker, fills)
            for fill in fills:
                log.info(
                    f"SHADOW FILL: {fill.side} {fill.size:.2f} @ {fill.price:.3f} "
                    f"[{token_id[:8]}] trade@{trade_price:.3f}"
                )
                await self._fills_q.put(fill)
